#version: "2.1"
#services:
#  jobmanager:
#    image: ${FLINK_IMAGE_NAME:-flink}
#    expose:
#      -  "6123"
#    ports:
#      - "8081:8081"
#    command: jobmanager
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#
#
#  taskmanager:
#    image: ${FLINK_DOCKER_IMAGE_NAME:-flink}
#    expose:
#      - "6121"
#      - "6122"
#    depends_on:
#      - jobmanager
#    command: taskmanager
#    links:
#      - "jobmanager:jobmanager"
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#
##  zookeeper:
##      image: wurstmeister/zookeeper:3.4.6
##      expose:
##        -2181



#version: '2'
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#  kafka-1:
#    image: spotify/kafka
#    container_name: kafka-1
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CREATE_TOPICS="input-topic:

version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka-1:
    image: spotify/kafka
    container_name: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_